### ISSUE TITLE
Unable to connect to non-password protected redis

### ISSUE THREAD

**Issue by rozhok** [node-vk-bot-api/node-vk-bot-api-session-redis#5]
Changes introduced in #1 broke connection to non-secured redis:

```
const session = new RedisSession({
  host: '51.51.51.51',
  port: '6379',
});
```

or

```
const session = new RedisSession({
  host: '51.51.51.51',
  port: '6379',
  password: ''
});
```

Results in 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^
ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/Users/kek/kekproject/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/Users/kek/kekproject/node_modules/redis-parser/lib/parser.js:303:14)
```

**Comment by rozhok** [comment]
There was indeed a password required on redis, I've misconfigured it.
